(() => {
  'use strict';
  const hero = document.querySelector('.hardware-hero');
  const scene = document.querySelector('.hardware-camera');
  const readout = document.getElementById('component-readout');
  const motion = document.getElementById('motion-toggle');
  const transmit = document.getElementById('transmit-demo');
  const reduced = matchMedia('(prefers-reduced-motion: reduce)');
  const fine = matchMedia('(pointer:fine)');
  let motionOn = !reduced.matches, timer = 0, raf = 0, selected = 'intro';
  const copy = {
    fr:{intro:['Une architecture de terrain','Touchez un repère pour explorer les composants du concept.'],radio:['01 · Antenne LoRa','Antenne verticale, connecteur et câble coaxial. Le boîtier peut accueillir une carte ESP32 / LoRa de type T-Beam.'],enclosure:['02 · Boîtier et fixation','Couvercle vissé, entrées de câbles sous le boîtier, colliers et support de mât. Étanchéité et dimensionnement restent à valider.'],solar:['03 · Alimentation solaire','Panneau sur support incliné. Batterie, régulateur et autonomie sont à dimensionner selon les capteurs et le site.'],edge:['04 · Calcul local','Boîtier à ailettes et ports réseau pour illustrer un nœud de calcul local. Ce rendu ne représente pas un modèle certifié.'],pause:'Mettre en pause',resume:'Activer l’animation',send:'Simuler une transmission',note:'Animation illustrative · aucune télémétrie réelle',preview:'Aperçu V2',current:'Voir le site actuel',concept:'Visualisation conceptuelle · assemblage à valider',products:'Produits numériques',productsTitle:'Des outils qui vous appartiennent.',budgetText:'Un budget adapté à votre paie, à vos paiements et à vos fournisseurs. Des catégories modifiables, des calculs automatiques.',budgetAction:'Essayer G1X Budget',priceNote:'Démo gratuite · conditions de la future version commerciale à définir.'},
    en:{intro:['A field-ready architecture concept','Select a marker to explore the proposed components.'],radio:['01 · LoRa antenna','Vertical antenna, connector and coaxial cable. The enclosure could house a T-Beam-type ESP32 / LoRa board.'],enclosure:['02 · Enclosure and mounting','Screwed lid, downward cable entries, clamps and mast bracket. Sealing and dimensions still require validation.'],solar:['03 · Solar power','Panel on an angled bracket. Battery, controller and autonomy must be sized for the sensors and location.'],edge:['04 · Local computing','Finned enclosure and network ports illustrate a local computing node. This rendering is not a certified product model.'],pause:'Pause motion',resume:'Enable motion',send:'Simulate transmission',note:'Illustrative animation · no live telemetry',preview:'V2 preview',current:'View current website',concept:'Concept visualization · assembly to be validated',products:'Digital products',productsTitle:'Tools that fit your life.',budgetText:'A budget that follows your income, payments and providers. Editable categories and automatic calculations.',budgetAction:'Try G1X Budget',priceNote:'Free demo · future commercial terms to be defined.'}
  };
  Object.assign(copy.fr,{sensor:['04 · Abri du capteur','Un abri à coupelles protège le capteur de température et d’humidité du rayonnement direct, tout en laissant circuler l’air.'],receiverTag:'Du terrain au calcul local',receiverTitle:'L’information arrive ici.',receiverText:'Le module ESP32 LoRa reçoit les messages radio et les transmet au Pi 5 par USB. Le serveur local les conserve et les rend disponibles aux outils G1X.',receiverDemo:'PARCOURS ILLUSTRATIF',receiverScreen:'Réception · stockage · visualisation',receiverCaption:'Visualisation inspirée du poste G1X réel · écrans de démonstration · disposition et matériel illustratifs.',flow1:'Balise sur le terrain',flow2:'ESP32 LoRa · USB',flow3:'Traitement local',flow4:'G1X-Control'});
  Object.assign(copy.en,{sensor:['04 · Sensor shield','A multi-plate shield protects the temperature and humidity sensor from direct radiation while allowing air to circulate.'],receiverTag:'From field to local computing',receiverTitle:'The information arrives here.',receiverText:'The ESP32 LoRa module receives radio messages and passes them to the Pi 5 over USB. The local server stores them and makes them available to G1X tools.',receiverDemo:'ILLUSTRATIVE DATA FLOW',receiverScreen:'Reception · storage · visualization',receiverCaption:'Visualization inspired by the real G1X workstation · demo screens · illustrative layout and hardware.',flow1:'Field sensor station',flow2:'ESP32 LoRa · USB',flow3:'Local processing',flow4:'G1X-Control'});
  function language(){return document.documentElement.lang==='en'?'en':'fr';}
  function render(){const c=copy[language()];readout.querySelector('strong').textContent=c[selected][0];readout.querySelector('p').textContent=c[selected][1];document.querySelectorAll('[data-preview-i18n]').forEach(el=>{el.textContent=c[el.dataset.previewI18n]||el.textContent;});motion.textContent=motionOn?c.pause:c.resume;motion.setAttribute('aria-pressed',String(!motionOn));transmit.textContent=c.send;}
  document.querySelectorAll('.hw-hotspot').forEach(button=>button.addEventListener('click',()=>{selected=button.dataset.part;document.querySelectorAll('.hw-hotspot').forEach(el=>el.setAttribute('aria-pressed',String(el===button)));render();}));
  hero.addEventListener('pointermove',event=>{if(!motionOn||reduced.matches||!fine.matches||raf)return;raf=requestAnimationFrame(()=>{const r=hero.getBoundingClientRect();scene.style.setProperty('--hw-x',`${((event.clientX-r.left)/r.width-.5)*9}px`);scene.style.setProperty('--hw-y',`${((event.clientY-r.top)/r.height-.5)*5}px`);raf=0;});},{passive:true});
  hero.addEventListener('pointerleave',()=>{scene.style.setProperty('--hw-x','0px');scene.style.setProperty('--hw-y','0px');},{passive:true});
  motion.addEventListener('click',()=>{motionOn=!motionOn;document.documentElement.classList.toggle('preview-motion-off',!motionOn);render();});
  transmit.addEventListener('click',()=>{selected='radio';render();if(!motionOn||reduced.matches)return;clearTimeout(timer);scene.classList.remove('is-transmitting');void scene.offsetWidth;scene.classList.add('is-transmitting');document.documentElement.classList.add('preview-logo-restart');requestAnimationFrame(()=>requestAnimationFrame(()=>document.documentElement.classList.remove('preview-logo-restart')));timer=setTimeout(()=>scene.classList.remove('is-transmitting'),2200);});
  reduced.addEventListener('change',()=>{if(reduced.matches){motionOn=false;document.documentElement.classList.add('preview-motion-off');render();}});
  document.addEventListener('visibilitychange',()=>document.documentElement.classList.toggle('preview-motion-off',document.hidden||!motionOn||reduced.matches));
  new MutationObserver(render).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
  document.documentElement.classList.toggle('preview-motion-off',!motionOn);render();
})();
