(() => {
 'use strict';
 const $=id=>document.getElementById(id), engine=window.G1XBudget, key='g1x-budget-public-demo-v1';
 const t={
 fr:{back:'Retour à l’aperçu',demo:'DÉMO PUBLIQUE · DONNÉES FICTIVES',lead:'Votre budget. Vos fournisseurs. Votre rythme.',privacy:'Les calculs se font dans votre navigateur. Aucun compte et aucune connexion bancaire.',setup:'Vos repères',month:'Mois à prévoir',balance:'Solde au début de ce mois · CAD',pay:'Revenu net par versement · CAD',frequency:'Fréquence',anchor:'Date repère de la paie',second:'Deuxième jour du mois (1–28)',datesNote:'Une date repère définit le rythme. Deux fois par mois = deux jours fixes; toutes les deux semaines = tous les 14 jours. Aucun décalage automatique pour les jours fériés.',income:'Revenus du mois',outgoing:'Paiements et épargne',available:'Revenus moins sorties',ending:'Solde final prévu',expenses:'Vos paiements',add:'Ajouter',providersNote:'Choisissez une catégorie et saisissez le fournisseur de votre choix. Les montants de départ sont fictifs.',schedule:'Échéancier du mois',scheduleNote:'Solde calculé à la fin de chaque journée. L’heure des transactions n’est pas modélisée.',save:'Conserver sur cet appareil',export:'Exporter mes données',reset:'Recharger l’exemple fictif',scope:'Prototype de planification. Les remboursements de dettes sont des sorties prévues; les intérêts, impôts et soldes de dettes ne sont pas calculés. Les provisions ne sont pas des prélèvements bancaires.',commercial:'Démo gratuite. Le tarif et les fonctions de la future version commerciale restent à définir.',editPayment:'Configurer un paiement',close:'Fermer',category:'Catégorie',label:'Nom du paiement',provider:'Fournisseur / organisme (facultatif)',amount:'Montant par paiement · CAD',paymentAnchor:'Date repère du paiement',recurrenceNote:'Mensuel : même jour chaque mois, ramené au dernier jour si nécessaire. Deux fois par mois : choisissez deux jours différents de 1 à 28.',apply:'Appliquer',edit:'Modifier',remove:'Retirer',noProvider:'Fournisseur libre',payLabel:'Paie',saved:'Enregistré dans ce navigateur uniquement.',restored:'Votre budget enregistré dans ce navigateur a été chargé.',saveFailed:'Le navigateur ne permet pas l’enregistrement. Vous pouvez exporter les données.',invalid:'Vérifiez les montants, les dates et les deux jours distincts (1–28) pour un paiement deux fois par mois.',exported:'Fichier exporté sur votre appareil.',reloaded:'Exemple fictif rechargé. La copie enregistrée a été supprimée.',removeConfirm:'Retirer ce paiement ?',resetConfirm:'Remplacer votre saisie et la copie enregistrée par l’exemple fictif ?',negative:'Attention : le solde prévu devient négatif au cours du mois.',noEvents:'Aucun mouvement prévu ce mois-ci.',cap:'Limite de cette démo : 100 paiements.',newPayment:'Nouveau paiement',choice:'Votre choix'},
 en:{back:'Back to preview',demo:'PUBLIC DEMO · FICTIONAL DATA',lead:'Your budget. Your providers. Your schedule.',privacy:'Calculations run in your browser. No account and no bank connection.',setup:'Your starting point',month:'Planning month',balance:'Opening balance for this month · CAD',pay:'Net income per payment · CAD',frequency:'Frequency',anchor:'Pay reference date',second:'Second day of month (1–28)',datesNote:'A reference date defines the schedule. Twice monthly = two fixed dates; every two weeks = every 14 days. No automatic public-holiday adjustment.',income:'Monthly income',outgoing:'Payments and savings',available:'Income minus outflows',ending:'Expected closing balance',expenses:'Your payments',add:'Add',providersNote:'Choose a category and enter any provider. The starting amounts are fictional.',schedule:'Monthly schedule',scheduleNote:'Balances are calculated at the end of each day. Transaction times are not modelled.',save:'Save on this device',export:'Export my data',reset:'Reload fictional example',scope:'Planning prototype. Debt repayments are planned outflows; interest, taxes and outstanding debt balances are not calculated. Savings allocations are not bank withdrawals.',commercial:'Free demo. Pricing and features of a future commercial version are yet to be defined.',editPayment:'Configure a payment',close:'Close',category:'Category',label:'Payment name',provider:'Provider / organisation (optional)',amount:'Amount per payment · CAD',paymentAnchor:'Payment reference date',recurrenceNote:'Monthly: the same day each month, capped to the last day when necessary. Twice monthly: choose two different days from 1 to 28.',apply:'Apply',edit:'Edit',remove:'Remove',noProvider:'Choose any provider',payLabel:'Pay',saved:'Saved in this browser only.',restored:'Your budget saved in this browser has been loaded.',saveFailed:'This browser does not allow saving. You can export the data.',invalid:'Check amounts, dates and the two distinct days (1–28) for twice-monthly payments.',exported:'File exported to your device.',reloaded:'Fictional example reloaded. The saved copy was removed.',removeConfirm:'Remove this payment?',resetConfirm:'Replace your entries and saved copy with the fictional example?',negative:'Warning: the projected balance becomes negative during the month.',noEvents:'No movements scheduled for this month.',cap:'This demo supports up to 100 payments.',newPayment:'New payment',choice:'Your choice'}
 };
 const freq={fr:{weekly:'Chaque semaine',biweekly:'Toutes les 2 semaines',semimonthly:'Deux fois par mois',monthly:'Chaque mois',quarterly:'Tous les 3 mois',yearly:'Chaque année'},en:{weekly:'Every week',biweekly:'Every 2 weeks',semimonthly:'Twice per month',monthly:'Every month',quarterly:'Every 3 months',yearly:'Every year'}};
 const cat={fr:{housing:'Logement / hypothèque',power:'Électricité',internet:'Internet',mobile:'Cellulaire',homeInsurance:'Assurance habitation',carInsurance:'Assurance auto',lifeInsurance:'Assurance vie',children:'Épargne enfants',municipal:'Taxes municipales',downPayment:'Mise de fonds',creditCard:'Carte de crédit',creditLine:'Marge de crédit',personalLine:'Marge personnelle',other:'Autre'},en:{housing:'Housing / mortgage',power:'Electricity',internet:'Internet',mobile:'Mobile phone',homeInsurance:'Home insurance',carInsurance:'Car insurance',lifeInsurance:'Life insurance',children:'Children’s savings',municipal:'Municipal taxes',downPayment:'Down payment',creditCard:'Credit card',creditLine:'Credit line',personalLine:'Personal credit line',other:'Other'}};
 let lang='fr',editId=null;
 function id(){return 'p-'+(crypto.randomUUID?crypto.randomUUID():String(Date.now())+'-'+Math.random().toString(36).slice(2));}
 function defaults(){const y=new Date().getFullYear(),jan=new Date(Date.UTC(y,0,1,12));jan.setUTCDate(1+(4-jan.getUTCDay()+7)%7);const month=`${y}-${String(new Date().getMonth()+1).padStart(2,'0')}`;const make=(category,label,amount,day,frequency='monthly',secondDay=15)=>({id:id(),category,label,provider:'',amount:String(amount),frequency,anchor:`${y}-01-${String(day).padStart(2,'0')}`,secondDay});return{version:1,month,balance:'1500',income:{label:'Paie',amount:'1100',frequency:'weekly',anchor:jan.toISOString().slice(0,10),secondDay:15},expenses:[make('housing','Logement',900,1),make('power','Électricité',120,10),make('internet','Internet',75,12),make('mobile','Cellulaire',45,20),make('homeInsurance','Assurance habitation',95,5),make('carInsurance','Assurance auto',85,5),make('lifeInsurance','Assurance vie',35,8),make('children','Épargne enfant 1',25,1,'semimonthly'),make('children','Épargne enfant 2',25,1,'semimonthly'),make('municipal','Provision taxes municipales',100,18),make('downPayment','Mise de fonds',40,1,'weekly'),make('creditCard','Paiement carte de crédit',80,20),make('creditLine','Paiement marge de crédit',50,15),make('personalLine','Paiement marge personnelle',45,25)]};}
 let data=defaults();
 function valid(d){if(!d||d.version!==1||!Array.isArray(d.expenses)||d.expenses.length>100||typeof d.income!=='object')throw Error('schema');for(const r of d.expenses){if(!r||typeof r.label!=='string'||r.label.length>80||typeof r.provider!=='string'||r.provider.length>80||!cat.fr[r.category])throw Error('row');}engine.compute(d,d.month);return d;}
 try{const saved=localStorage.getItem(key);if(saved){data=valid(JSON.parse(saved));$('storage-status').textContent=t[lang].restored;}}catch{ $('storage-status').textContent='La copie locale n’a pas pu être chargée; l’exemple fictif est affiché.'; }
 function optionList(el,values,value){el.replaceChildren();for(const [v,name] of Object.entries(values)){const o=document.createElement('option');o.value=v;o.textContent=name;el.append(o);}el.value=value;}
 function cash(cents){return new Intl.NumberFormat(lang==='fr'?'fr-CA':'en-CA',{style:'currency',currency:'CAD'}).format(cents/100);}
 function element(tag,text,className){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(className)el.className=className;return el;}
 function syncInputs(){ $('month').value=data.month;$('balance').value=data.balance;$('pay').value=data.income.amount;$('pay-anchor').value=data.income.anchor;$('pay-second').value=data.income.secondDay;optionList($('pay-frequency'),freq[lang],data.income.frequency);$('pay-second-wrap').hidden=data.income.frequency!=='semimonthly'; }
 function readInputs(){data.month=$('month').value;data.balance=$('balance').value;data.income.amount=$('pay').value;data.income.frequency=$('pay-frequency').value;data.income.anchor=$('pay-anchor').value;data.income.secondDay=Number($('pay-second').value);data.income.label=t[lang].payLabel;$('pay-second-wrap').hidden=data.income.frequency!=='semimonthly';}
 function renderExpenses(){const box=$('expenses');box.replaceChildren();for(const row of data.expenses){const wrap=element('article',undefined,'expense-row'),left=element('div'),right=element('div',undefined,'expense-right');left.append(element('p',row.label,'expense-name'),element('p',`${cat[lang][row.category]} · ${row.provider||t[lang].noProvider}`,'expense-meta'));right.append(element('span',cash(engine.money(row.amount)),'expense-value'),element('p',freq[lang][row.frequency],'expense-meta'));const actions=element('div',undefined,'expense-actions');const edit=element('button',t[lang].edit);edit.type='button';edit.setAttribute('aria-label',`${t[lang].edit} ${row.label}`);edit.addEventListener('click',()=>openEditor(row));const remove=element('button',t[lang].remove);remove.type='button';remove.setAttribute('aria-label',`${t[lang].remove} ${row.label}`);remove.addEventListener('click',()=>{if(confirm(t[lang].removeConfirm)){data.expenses=data.expenses.filter(item=>item.id!==row.id);renderExpenses();calculate();}});actions.append(edit,remove);right.append(actions);wrap.append(left,right);box.append(wrap);}}
 function calculate(){try{readInputs();const result=engine.compute(data,data.month);$('error').hidden=true;for(const name of ['income','outgoing','available','ending']){const el=$('total-'+name);el.textContent=cash(result[name]);el.classList.toggle('negative',result[name]<0);}$('warning').hidden=result.minimum>=0;$('warning').textContent=t[lang].negative;const list=$('schedule');list.replaceChildren();for(const day of result.days){const card=element('div',undefined,'day'),head=element('div',undefined,'day-head');head.append(element('span',new Intl.DateTimeFormat(lang==='fr'?'fr-CA':'en-CA',{day:'numeric',month:'short',weekday:'short',timeZone:'UTC'}).format(engine.date(day.date))),element('strong',cash(day.balance),day.balance<0?'negative':''));card.append(head);for(const event of day.events){const line=element('div',undefined,`event ${event.cents>=0?'inflow':'outflow'}`);line.append(element('span',event.label+(event.provider?' · '+event.provider:'')),element('span',(event.cents>=0?'+':'−')+cash(Math.abs(event.cents))));card.append(line);}list.append(card);}if(!result.days.length)list.append(element('p',t[lang].noEvents,'hint'));return true;}catch{$('error').hidden=false;$('error').textContent=t[lang].invalid;for(const name of ['income','outgoing','available','ending'])$('total-'+name).textContent='—';$('schedule').replaceChildren();$('warning').hidden=true;return false;}}
 function translate(){document.documentElement.lang=lang;document.querySelectorAll('[data-t]').forEach(el=>el.textContent=t[lang][el.dataset.t]);document.querySelectorAll('[data-lang]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.lang===lang)));$('e-provider').placeholder=t[lang].choice;syncInputs();renderExpenses();calculate();}
 function openEditor(row){if(!row&&data.expenses.length>=100){$('error').hidden=false;$('error').textContent=t[lang].cap;return;}editId=row?.id||null;const current=row||{category:'other',label:'',provider:'',amount:'',frequency:'monthly',anchor:data.month+'-01',secondDay:15};optionList($('e-category'),cat[lang],current.category);optionList($('e-frequency'),freq[lang],current.frequency);$('e-label').value=current.label;$('e-provider').value=current.provider;$('e-amount').value=current.amount;$('e-anchor').value=current.anchor;$('e-second').value=current.secondDay;$('e-second-wrap').hidden=current.frequency!=='semimonthly';$('edit-error').textContent='';$('editor').showModal();}
 ['month','balance','pay','pay-frequency','pay-anchor','pay-second'].forEach(name=>$(name).addEventListener('input',calculate));
 document.querySelectorAll('[data-lang]').forEach(el=>el.addEventListener('click',()=>{readInputs();lang=el.dataset.lang;translate();}));
 $('add').addEventListener('click',()=>openEditor());$('close').addEventListener('click',()=>$('editor').close());$('e-frequency').addEventListener('change',()=>{$('e-second-wrap').hidden=$('e-frequency').value!=='semimonthly';});
 $('expense-form').addEventListener('submit',event=>{event.preventDefault();const row={id:editId||id(),category:$('e-category').value,label:$('e-label').value.trim(),provider:$('e-provider').value.trim(),amount:$('e-amount').value.trim(),frequency:$('e-frequency').value,anchor:$('e-anchor').value,secondDay:Number($('e-second').value)};try{if(!row.label)throw Error('label');engine.money(row.amount);engine.dates(row,data.month);if(editId)data.expenses=data.expenses.map(old=>old.id===editId?row:old);else data.expenses.push(row);$('editor').close();renderExpenses();calculate();}catch{$('edit-error').textContent=t[lang].invalid;}});
 $('save').addEventListener('click',()=>{if(!calculate())return;try{localStorage.setItem(key,JSON.stringify(data));$('storage-status').textContent=t[lang].saved;}catch{$('storage-status').textContent=t[lang].saveFailed;}});
 $('export').addEventListener('click',()=>{if(!calculate())return;const url=URL.createObjectURL(new Blob([JSON.stringify({...data,application:'G1X Budget',currency:'CAD'},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`g1x-budget-${data.month}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('storage-status').textContent=t[lang].exported;});
 $('reset').addEventListener('click',()=>{if(!confirm(t[lang].resetConfirm))return;data=defaults();try{localStorage.removeItem(key);}catch{}translate();$('storage-status').textContent=t[lang].reloaded;});
 translate();
})();
